import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { roboto } from "./ui/fonts";
import Menu from "./components/Menu";
import { Box } from "@mui/material";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}`}
      >
        <Box sx={{ display: 'flex', flexDirection: 'row' }}>
          <Menu />
          <div className="bg-gray-100 w-full ml-[30vh]">
            <div className="bg-gray-100 w-full p-5 " style={{ minHeight: '80vh' }}>
              {children}
            </div>
            <Footer/>
          </div>

        </Box>
      </body>
    </html>
  );
}
